//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuafor_randevuV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiyat_listesi
    {
        public int id { get; set; }
        public string hizmet { get; set; }
        public string fiyat { get; set; }
        public string süre { get; set; }
    }
}
