//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuafor_randevuV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kuafor_randevuEntities1 : DbContext
    {
        public kuafor_randevuEntities1()
            : base("name=kuafor_randevuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fiyat_listesi> fiyat_listesi { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<calisanlar> calisanlar { get; set; }
        public virtual DbSet<hizmet_turleri> hizmet_turleri { get; set; }
        public virtual DbSet<uygun_randevu> uygun_randevu { get; set; }
        public virtual DbSet<admin> admin { get; set; }
    }
}
