//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuafor_randevuV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu
    {
        public int id { get; set; }
        public string ad_soyad { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string randevu_tarih { get; set; }
        public string hizmet_turu { get; set; }
        public string personel { get; set; }
    }
}
